### ISSUE TITLE
making test_input.json to accept model parameter

### ISSUE THREAD

**Issue by askbekzod** [sky24h/AnimateDiff_Serverless_Runpod#1]
This repo's _inference_v2.yaml_ is different from original repo and new file _inference_util.py_ is added which is great. However any idea what file to edit so _test_input.json_ string will generate gif using say majicmixRealistic_v5Preview instead of realisticVisionV51_v20Novae.safetensors?

**Comment by askbekzod** [comment]
In test_input.json I added **boy** keyword "input": {
        "prompt": "boy" ... } because  inference_util.py says self.person_prompts = ["boy", "girl", "man", "woman", "person", "eye", "face"]. However model did not change.

**Comment by askbekzod** [comment]
nevermind, it works properly, I got it. If anyone was confused edit Scene and Person attribute inside inference_v2.yaml for whichever model you like. Then you can edit inference_util.py for any triggering keywords from your prompt. Finally use keyword that you like inside test_input.json. So no need for model parameter

**Comment by sky24h** [comment]
Hi, @askbekzod.
Thank you for your comment.
It seems like you have already found the solutions🥳. 
I was just about to reply to you.😂

Maybe I should add the triggering keywords to the inference_v2.yaml file for easier understanding and editing?

**Comment by askbekzod** [comment]
Hi! For your use case, where user sends only string input, keeping trigger keywords in Python is better.  The best option is however to send json where we specify model parameter {"motion_module": "mm_sd_v15",
           "model":"toonyou_beta3.safetensors",
           "prompt":"tree, masterpiece",
           "steps": 25,
           "guidance_scale": 7.5,
           "seed": 13204175718326964000
           }.  It is better because let's say I want a gif of a tree in photorealistic 3d and in cartoon 3d style. In your implementation I cannot use keyword 3d. Thus will have to come up with unique tag or pass modelname inside an input string in test_input.json. That is why for your case it is better to keep triggers inside inference_util.py, so right after `if keyword in prompt:    isPerson = True` we can crop out tag word or model name so it does not influence our generation. Note I only described overlap between 2 models. There are about 10 of them for animatediff😅 But for Person and Not Person it is OK, otherwise model parameter is musthave

**Comment by askbekzod** [comment]
by the way you should apply for referal program on runpod for serverless and insert link to github repo. So people using your repo can support you. I will send details to email displayed on your Github profile

**Comment by sky24h** [comment]
> The best option is however to send json where we specify model parameter 

Thank you for your advice.
Yes, you are right, most of the model parameters should be changeable by the input side to avoid frequent rebuilds.
I'm considering letting most model parameters be overridden by the input strings, while default settings will be used if not specified.
This way, users with more experience can easily specify them by simply changing the input json.

Additionally, the recently released motion Lora models (by the author of AnimateDiff) are difficult to switch by keywords, so it may be easier to specify them through the json.

> by the way you should apply for referal program on runpod for serverless and insert link to github repo. So people using your repo can support you. I will send details to email displayed on your Github profile

Thank you, will do!
