### ISSUE TITLE
server.py isn't returning the status from RunPod

### ISSUE THREAD

**Issue by JustinWallace-MOM** [sky24h/AnimateDiff_Serverless_Runpod#2]
`test_client.py`'s request succeeds, but errors out when saving the image because the `status` key isn't defined in what `server.py` is returning.

`KeyError: 'status'`

This should be simple, but my brain is just not getting it.

**Comment by sky24h** [comment]
`status` key is not defined by `server.py`, it's defined by RunPod's API by default, to indicate the status of the request.
https://docs.runpod.io/reference/runpod-apis

I'm not sure what's happening here, have you passed the local test before deploying to RunPod?
And, could you provide your output in [this](https://github.com/sky24h/AnimateDiff_Serverless_Runpod/blob/baf4a686e222c999e04c444a40a28b7562cb5881/test_client.py#L27C1-L27C31) line?

**Comment by JustinWallace-MOM** [comment]
A local build works, and saves the output in the tmp folder.

test_client.py returns this. The data property returns a giant string string of base64, which I cut out for brevity:

`Sending request...
Got response! {'data': 'cutting this out temporarily', 'filename': '195577361_z9eoq3va.mp4'}
Traceback (most recent call last):
  File "/home/justin/Documents/AnimateDiff_Serverless_Runpod-main/test_client.py", line 31, in <module>
    if result["status"] == "COMPLETED":
KeyError: 'status'
`

Thanks for the help here!

**Comment by sky24h** [comment]
Sorry for the late reply.
After reviewing the situation, I figured out the issue was caused by the update of Runpod's API. 
The structure of the returned object has changed.
https://github.com/runpod/runpod-python/blob/ef7f1bc526cfe38d6837b0205b8aa06ba817dfb7/runpod/endpoint/runner.py#L113

I've [updated](https://github.com/sky24h/AnimateDiff_Serverless_Runpod/commit/9d5a2ec77ee014de092f4eaa12e65449fbe9f49d) the code to align with the latest version and have specified the version to avoid similar issues in the future.
The output should now be like this:

> Sending request...
> Got response! IN_QUEUE
> Waiting for completion... (0/120)
> Waiting for completion... (5/120)
> Waiting for completion... (10/120)
> Waiting for completion... (15/120)
> Waiting for completion... (20/120)
> Waiting for completion... (25/120)
> Waiting for completion... (30/120)
> Waiting for completion... (35/120)
> Waiting for completion... (40/120)
> Waiting for completion... (45/120)
> Waiting for completion... (50/120)
> Waiting for completion... (55/120)
> Waiting for completion... (60/120)
> Generation completed successfully!
> Here's your image:
> Saved to /tmp/195577361_lhmfarvp.mp4

**Comment by JustinWallace-MOM** [comment]
This worked wonderfully, and I see you fixed the model naming and motion_lora conditional as well!

You're the best. Thanks so much!

**Comment by iminahiljaved** [comment]
> This worked wonderfully, and I see you fixed the model naming and motion_lora conditional as well!
> 
> You're the best. Thanks so much!
Can you guide me how you got it working?
