### ISSUE TITLE
what to do after making endpoint?

### ISSUE THREAD

**Issue by iminahiljaved** [sky24h/AnimateDiff_Serverless_Runpod#4]
I am unclear on when i make endpoint on runpod, what to do next , i mean how to use it?

**Comment by sky24h** [comment]
An endpoint is an API, that receives a request and returns a generated video to where you send the request.
For instance, at the end of README, there is a showcase where users can send a text to request a generated video without coding.

If you were asking how to call the API, please refer to "test_client.py".

**Comment by iminahiljaved** [comment]
okay i'll check, make docker image , place the image name in build.sh, deploy it and make endpoint , call it using test_client.py

**Comment by iminahiljaved** [comment]
In the dockerfile should the last line should stay commented ?

# Run server
CMD [ "python", "-u", "./server.py" ]
# ADD ./test_input.json ./    <----this line

**Comment by iminahiljaved** [comment]
am getting this contiuosly , any reaso why?
Sending request...
Got response! IN_QUEUE
Waiting for completion... (0/120)
Waiting for completion... (5/120)
Waiting for completion... (10/120)
Waiting for completion... (15/120)
Waiting for completion... (20/120)
Waiting for completion... (25/120)
Waiting for completion... (30/120)
Waiting for completion... (35/120)
Waiting for completion... (40/120)
Waiting for completion... (45/120)
Waiting for completion... (50/120)
Waiting for completion... (60/120)
Waiting for completion... (65/120)
Waiting for completion... (70/120)
Waiting for completion... (75/120)
Waiting for completion... (80/120)
Waiting for completion... (85/120)
Waiting for completion... (90/120)
Waiting for completion... (95/120)
Waiting for completion... (100/120)
Waiting for completion... (105/120)
Waiting for completion... (110/120)
Waiting for completion... (115/120)
Waiting for completion... (120/120)
Timeout !

**Comment by iminahiljaved** [comment]
FYI i even increased the time out

**Comment by sky24h** [comment]
> In the dockerfile should the last line should stay commented ?
> 
> # Run server
> CMD [ "python", "-u", "./server.py" ]
> 
> # ADD ./test_input.json ./ <----this line

This is only for debugging and is not required for deployment.

**Comment by sky24h** [comment]
> am getting this contiuosly , any reaso why? Sending request... Got response! IN_QUEUE Waiting for completion... (0/120) Waiting for completion... (5/120) Waiting for completion... (10/120) Waiting for completion... (15/120) Waiting for completion... (20/120) Waiting for completion... (25/120) Waiting for completion... (30/120) Waiting for completion... (35/120) Waiting for completion... (40/120) Waiting for completion... (45/120) Waiting for completion... (50/120) Waiting for completion... (60/120) Waiting for completion... (65/120) Waiting for completion... (70/120) Waiting for completion... (75/120) Waiting for completion... (80/120) Waiting for completion... (85/120) Waiting for completion... (90/120) Waiting for completion... (95/120) Waiting for completion... (100/120) Waiting for completion... (105/120) Waiting for completion... (110/120) Waiting for completion... (115/120) Waiting for completion... (120/120) Timeout !

It means something wrong occurred during the generation. 
Firstly, have you succeeded in the local test (python server.py)? 
If you passed the local test but still got this timeout, try to check the logs at the runpod endpoint side to find out what happened during the generation.

**Comment by iminahiljaved** [comment]
> > am getting this contiuosly , any reaso why? Sending request... Got response! IN_QUEUE Waiting for completion... (0/120) Waiting for completion... (5/120) Waiting for completion... (10/120) Waiting for completion... (15/120) Waiting for completion... (20/120) Waiting for completion... (25/120) Waiting for completion... (30/120) Waiting for completion... (35/120) Waiting for completion... (40/120) Waiting for completion... (45/120) Waiting for completion... (50/120) Waiting for completion... (60/120) Waiting for completion... (65/120) Waiting for completion... (70/120) Waiting for completion... (75/120) Waiting for completion... (80/120) Waiting for completion... (85/120) Waiting for completion... (90/120) Waiting for completion... (95/120) Waiting for completion... (100/120) Waiting for completion... (105/120) Waiting for completion... (110/120) Waiting for completion... (115/120) Waiting for completion... (120/120) Timeout !
> 
> It means something wrong occurred during the generation. Firstly, have you succeeded in the local test (python server.py)? If you passed the local test but still got this timeout, try to check the logs at the runpod endpoint side to find out what happened during the generation.

I couldnt check it locally as i didnt have gpu , i made a docker image directly , i tried to run it on colab but couldnt figure out , maybe i am doing something wrong , i followed the exact steps in readme
also i checked the logs in runpod and got weird errors
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /workspace/models/StableDiffusion/stable-diffusion-v1-5.
2024-03-05 15:51:02.223
[9tg7tdv9ec76th]
[info]
raise EnvironmentError(
2024-03-05 15:51:02.223
[9tg7tdv9ec76th]
[info]
File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2449, in from_pretrained
2024-03-05 15:51:02.223
[9tg7tdv9ec76th]
[info]
text_encoder = CLIPTextModel.from_pretrained(pretrained_model_path, subfolder="text_encoder", torch_dtype=dtype)
2024-03-05 15:51:02.223
[9tg7tdv9ec76th]
[info]
File "/workspace/animatediff/utils/util.py", line 111, in init_pipeline
2024-03-05 15:51:02.223
[9tg7tdv9ec76th]
[info]
self.pipeline = init_pipeline(pretrained_model_path, self.inference_config, self.device, self.dtype)
2024-03-05 15:51:02.223
[9tg7tdv9ec76th]
[info]
File "/workspace/inference_util.py", line 116, in __init__
2024-03-05 15:51:02.223
[9tg7tdv9ec76th]
[info]
animatediff = AnimateDiff()
2024-03-05 15:51:02.223
[9tg7tdv9ec76th]
[info]
File "/workspace/./server.py", line 13, in <module>
2024-03-05 15:51:02.223
[9tg7tdv9ec76th]
[info]
Traceback (most recent call last):
2024-03-05 15:50:43.979
[9tg7tdv9ec76th]
[info]

**Comment by iminahiljaved** [comment]
> > > am getting this contiuosly , any reaso why? Sending request... Got response! IN_QUEUE Waiting for completion... (0/120) Waiting for completion... (5/120) Waiting for completion... (10/120) Waiting for completion... (15/120) Waiting for completion... (20/120) Waiting for completion... (25/120) Waiting for completion... (30/120) Waiting for completion... (35/120) Waiting for completion... (40/120) Waiting for completion... (45/120) Waiting for completion... (50/120) Waiting for completion... (60/120) Waiting for completion... (65/120) Waiting for completion... (70/120) Waiting for completion... (75/120) Waiting for completion... (80/120) Waiting for completion... (85/120) Waiting for completion... (90/120) Waiting for completion... (95/120) Waiting for completion... (100/120) Waiting for completion... (105/120) Waiting for completion... (110/120) Waiting for completion... (115/120) Waiting for completion... (120/120) Timeout !
> > 
> > 
> > It means something wrong occurred during the generation. Firstly, have you succeeded in the local test (python server.py)? If you passed the local test but still got this timeout, try to check the logs at the runpod endpoint side to find out what happened during the generation.
> 
> I couldnt check it locally as i didnt have gpu , i made a docker image directly , i tried to run it on colab but couldnt figure out , maybe i am doing something wrong , i followed the exact steps in readme also i checked the logs in runpod and got weird errors OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /workspace/models/StableDiffusion/stable-diffusion-v1-5. 2024-03-05 15:51:02.223 [9tg7tdv9ec76th] [info] raise EnvironmentError( 2024-03-05 15:51:02.223 [9tg7tdv9ec76th] [info] File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2449, in from_pretrained 2024-03-05 15:51:02.223 [9tg7tdv9ec76th] [info] text_encoder = CLIPTextModel.from_pretrained(pretrained_model_path, subfolder="text_encoder", torch_dtype=dtype) 2024-03-05 15:51:02.223 [9tg7tdv9ec76th] [info] File "/workspace/animatediff/utils/util.py", line 111, in init_pipeline 2024-03-05 15:51:02.223 [9tg7tdv9ec76th] [info] self.pipeline = init_pipeline(pretrained_model_path, self.inference_config, self.device, self.dtype) 2024-03-05 15:51:02.223 [9tg7tdv9ec76th] [info] File "/workspace/inference_util.py", line 116, in **init** 2024-03-05 15:51:02.223 [9tg7tdv9ec76th] [info] animatediff = AnimateDiff() 2024-03-05 15:51:02.223 [9tg7tdv9ec76th] [info] File "/workspace/./server.py", line 13, in 2024-03-05 15:51:02.223 [9tg7tdv9ec76th] [info] Traceback (most recent call last): 2024-03-05 15:50:43.979 [9tg7tdv9ec76th] [info]

As far as i can understand from this error there should be a few files in stable-diffusion-v1-5 but are not there

**Comment by iminahiljaved** [comment]
no reply? can you please give me your email or anything so i can contact you

**Comment by sky24h** [comment]
Sorry for not getting back to you sooner, I'm currently traveling.
I just tried running a test on Colab and it works normally.
Please take a look at the updated example notebook in the [README](https://github.com/sky24h/AnimateDiff_Serverless_Runpod?tab=readme-ov-file#2-dependencies).

It means the code is just functioning properly. However, I'm not sure how to build a Docker image from Colab. 
You might want to look it up on Google or consider renting a Runpod instance for an hour to do this.

Unfortunately, I can't help you with all the details since I'm not paid for this project.
However, I might offer some hints or bug fixes when possible, purely on a voluntary basis.

**Comment by iminahiljaved** [comment]
> Sorry for not getting back to you sooner, I'm currently traveling. I just tried running a test on Colab and it works normally. Please take a look at the updated example notebook in the [README](https://github.com/sky24h/AnimateDiff_Serverless_Runpod?tab=readme-ov-file#2-dependencies).
> 
> It means the code is just functioning properly. However, I'm not sure how to build a Docker image from Colab. You might want to look it up on Google or consider renting a Runpod instance for an hour to do this.
> 
> Unfortunately, I can't help you with all the details since I'm not paid for this project. However, I might offer some hints or bug fixes when possible, purely on a voluntary basis.

Thankyou so much , the colab notebook is working whcih means i am making some silly mistake while making docker image, still if you or anyone has any guidance on docker image making it will be also great

**Comment by iminahiljaved** [comment]
can we somehow increase the time of the video?

**Comment by sky24h** [comment]
The video length (number of frames) can be changed at [here](https://github.com/sky24h/AnimateDiff_Serverless_Runpod/blob/94884cc3d0cce6bb247381df6cdaf7833a2220ab/inference_util.py#L111C14-L111C26), however, the generation quality is not guaranteed.
Please refer to the [explanation](https://github.com/guoyww/AnimateDiff?tab=readme-ov-file#common-issues) (Various resolution or number of frames) of the original model.
